databases:
  - name: care-worker-db
    databaseName: care_worker_training
    user: care_worker_user
    plan: free

services:
  - type: web
    name: care-worker-training
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: care-worker-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false